jobs:
- job: LinuxContainerBuilds
  strategy:
    matrix:
      base:
        imageName: 'aosc-os'
      buildkit:
        imageName: 'aosc-os-buildkit'
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - bash: ./.ci/build-latest.sh 'amd64' '$(imageName)'
  - task: Docker@1
    displayName: Container registry login
    inputs:
      command: login
      containerregistrytype: Container Registry
      dockerRegistryEndpoint: docker
  - task: Docker@1
    displayName: Push image
    inputs:
      command: push
      imageName: 'aosc/$(imageName)'
